version: '2.1'

services:

  promociones-db:
    build: ./db
    environment:
      MYSQL_DATABASE: Promociones
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 1234
      DATABASE_HOST: db
    ports:
      - 3309:3306

  promociones-ms:
    build: .
    environment:
      NODE_ENV: production
      DATABASE_HOST: promociones-db
      MYSQL_PORT: 3309
      MYSQL_DATABASE: Promociones
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 1234
    ports:
      - "3004:3004"
    depends_on:
      - promociones-db
    restart: on-failure
